; Demo Script AHK untuk Deteksi Jenis Transaksi BNB/BNS
; File: demo-bns-bnb-detection.ahk
; Generated by: MBA Transaction System v1.4.1

; === FUNGSI HELPER ===
TypeString(str) {
    Loop Parse, str
    {
        Send %A_LoopField%
        Sleep 0
    }
}

; === DATA NASABAH ===
; Nama: Demo BNB-BNS Detection
; Alamat: Jl. Test Mixed Transaction
; Telepon: 08123456789
; Pekerjaan: Tester
; No. Identitas: 1234567890
; Tempat Lahir: Jakarta
; Tanggal Lahir: 01-01-1990

; === MULAI SCRIPT ===
; Pastikan aplikasi MBA sudah terbuka
WinWait, Data Prosesing PT Mulia Bumi Arta, , 10
if ErrorLevel {
    MsgBox, 48, Error, Aplikasi MBA tidak ditemukan! Pastikan aplikasi sudah dibuka.
    ExitApp
}

; Aktifkan window aplikasi
WinActivate, Data Prosesing PT Mulia Bumi Arta
Sleep, 500

; === ISI DATA NASABAH ===
; Nama
TypeString("Demo BNB-BNS Detection")
Send, {Tab}
Sleep, 200

; Alamat
TypeString("Jl. Test Mixed Transaction")
Send, {Tab}
Sleep, 200

; Telepon
TypeString("08123456789")
Send, {Tab}
Sleep, 200

; Pekerjaan
TypeString("Tester")
Send, {Tab}
Sleep, 200

; No. Identitas
TypeString("1234567890")
Send, {Tab}
Sleep, 200

; Tempat Lahir
TypeString("Jakarta")
Send, {Tab}
Sleep, 200

; Tanggal Lahir
TypeString("01-01-1990")
Sleep, 200

; === NAVIGASI KE BAGIAN TRANSAKSI ===
; Total transaksi yang akan diproses: 3
; Setelah mengisi Tempat Tanggal Lahir, langsung ke transaksi
Sleep, 200

; Pastikan window masih aktif
WinActivate, Data Prosesing PT Mulia Bumi Arta
Sleep, 100

; Enter 2x untuk navigasi ke field Code Currency (tanpa delay)
Send, {Enter}
Sleep, 200
Send, {Enter}
Sleep, 200

; === ISI DATA TRANSAKSI 1 ===
; Debug: Currency input = "USD", Code = 1
; Jenis Transaksi: BNB
; Isi Code Currency USD = 1
Send, 1
Sleep, 200

; Enter 2x untuk navigasi ke field Amount (cepat)
Send, {Enter}
Sleep, 200
Send, {Enter}
Sleep, 200

; Isi Amount 1000
TypeString("1000")
Sleep, 100

; Enter 1x untuk navigasi ke field Exchange Rate (cepat)
Send, {Enter}
Sleep, 200

; Isi Exchange Rate 15000
TypeString("15000")
Sleep, 100

; Enter untuk konfirmasi baris transaksi
Send, {Enter}
Sleep, 200

; === NAVIGASI KE BARIS TRANSAKSI 2 (NORMAL) ===
; Enter 2x untuk navigasi ke baris transaksi berikutnya (cepat)
Send, {Enter}
Sleep, 200
Send, {Enter}
Sleep, 200

; === ISI DATA TRANSAKSI 2 ===
; Debug: Currency input = "EUR", Code = 4
; Jenis Transaksi: BNS
; Jenis transaksi BNS - navigasi khusus sebelum input
Send, {Right}
Sleep, 200

; Isi Code Currency EUR = 4
Send, 4
Sleep, 200

; Enter 2x untuk navigasi ke field Amount (cepat)
Send, {Enter}
Sleep, 200
Send, {Enter}
Sleep, 200

; Isi Amount 500
TypeString("500")
Sleep, 100

; Enter 1x untuk navigasi ke field Exchange Rate (cepat)
Send, {Enter}
Sleep, 200

; Isi Exchange Rate 16000
TypeString("16000")
Sleep, 100

; Enter untuk konfirmasi baris transaksi
Send, {Enter}
Sleep, 200

; === NAVIGASI KE BARIS TRANSAKSI 3 (NORMAL) ===
; Enter 2x untuk navigasi ke baris transaksi berikutnya (cepat)
Send, {Enter}
Sleep, 200
Send, {Enter}
Sleep, 200

; === ISI DATA TRANSAKSI 3 ===
; Debug: Currency input = "GBP", Code = 5
; Jenis Transaksi: BNB
; Isi Code Currency GBP = 5
Send, 5
Sleep, 200

; Enter 2x untuk navigasi ke field Amount (cepat)
Send, {Enter}
Sleep, 200
Send, {Enter}
Sleep, 200

; Isi Amount 300
TypeString("300")
Sleep, 100

; Enter 1x untuk navigasi ke field Exchange Rate (cepat)
Send, {Enter}
Sleep, 200

; Isi Exchange Rate 18000
TypeString("18000")
Sleep, 100

; Enter untuk konfirmasi baris transaksi
Send, {Enter}
Sleep, 200

; Navigasi selesai - 3 transaksi telah diproses
Sleep, 300

; Enter 1x untuk mengakhiri input transaksi
Send, {Enter}
Sleep, 300

Sleep 500
MsgBox, 64, Success, Script Completed - Demo BNB/BNS Detection berhasil!`nTransaksi 1 (USD): BNB - Navigasi Normal`nTransaksi 2 (EUR): BNS - Navigasi Khusus (Right Arrow)`nTransaksi 3 (GBP): BNB - Navigasi Normal
FileDelete, %A_ScriptFullPath%
ExitApp
